[Interface]
Address = 10.13.13.4
PrivateKey = uFqOsZxcN5JlAwUQuYqfx7tgGDB6wFPeu3itkRMMU2U=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = xQWpaO7PZJ4VJUVSELdQusK1H0Rn5+sgm6ubWVHK2jk=
PresharedKey = ubdVtm84uGVp3P9LEvBecDTqd5PI0z1V/Yl1KElIMEc=
Endpoint = 192.168.100.1:51820
AllowedIPs = 10.13.13.0/24
PersistentKeepalive = 25