Vagrant.configure("2") do |config|
  config.vm.box = "alvistack/ubuntu-24.04"
  config.vm.hostname = "worker-1"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 18384
    vb.cpus = 16
  end

  config.vm.provision "file", source: "../k3s", destination: "/tmp/k3s"
  config.vm.provision "shell", inline: <<-SHELL
    sudo mv /tmp/k3s /usr/local/bin/ && sudo chmod 777 /usr/local/bin/k3s
  SHELL

  config.vm.provision "file", source: "peer3.conf", destination: "/tmp/wireguard/wg0.conf"
  config.vm.provision "shell", inline: <<-SHELL
    sudo mkdir -p /etc/wireguard/ && sudo mv /tmp/wireguard/wg0.conf /etc/wireguard/wg0.conf
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    sudo wg-quick down wg0 || true
    sudo apt update
    DEBIAN_FRONTEND=noninteractive sudo apt install -y wireguard net-tools nfs-kernel-server
    sudo systemctl enable wg-quick@wg0
    sudo systemctl start wg-quick@wg0
    sudo wg-quick up wg0 || true
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    export INSTALL_K3S_SKIP_DOWNLOAD=true
    curl -sfL https://get.k3s.io | K3S_URL="https://10.13.13.3:6443" K3S_TOKEN="dsteam123" sh -s - --node-external-ip=10.13.13.4 --node-ip=10.13.13.4 --flannel-iface=wg0
  SHELL
end
