[Interface]
Address = 10.13.13.3
PrivateKey = ALIMiJLJjgovLHoh0F75TQJQMTYUjzr/ctWsDkP9N1U=
ListenPort = 51820
DNS = 8.8.8.8

[Peer]
PublicKey = xQWpaO7PZJ4VJUVSELdQusK1H0Rn5+sgm6ubWVHK2jk=
PresharedKey = 04HrqIumQcN2x9qLvYWxHi5BJL8C2gnodgL0nq6J+4I=
Endpoint = 192.168.100.1:51820
AllowedIPs = 10.13.13.0/24
PersistentKeepalive = 25

